all:
	gcc -o usb.out -I/usr/local/include/libusb-1.0 libusb_demo.c -L/usr/local/lib -lusb-1.0
dbg:
	gcc -o usb.out -g -I/usr/local/include/libusb-1.0 libusb_demo.c -L/usr/local/lib -lusb-1.0
clean:
	rm *.out
