# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_default = QtWidgets.QGridLayout()
        self.gridLayout_default.setObjectName("gridLayout_default")
        self.gridLayout.addLayout(self.gridLayout_default, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPlugins = QtWidgets.QMenu(parent=self.menubar)
        self.menuPlugins.setObjectName("menuPlugins")
        self.menuPreferences = QtWidgets.QMenu(parent=self.menubar)
        self.menuPreferences.setObjectName("menuPreferences")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionListWindows = QtGui.QAction(parent=MainWindow)
        self.actionListWindows.setObjectName("actionListWindows")
        self.actionEditors = QtGui.QAction(parent=MainWindow)
        self.actionEditors.setObjectName("actionEditors")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionTools = QtGui.QAction(parent=MainWindow)
        self.actionTools.setObjectName("actionTools")
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuHelp.addAction(self.actionAbout)
        self.menuPlugins.addAction(self.actionEditors)
        self.menuPlugins.addSeparator()
        self.menuPreferences.addAction(self.actionSettings)
        self.menubar.addAction(self.menuPlugins.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "hamster"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuPlugins.setTitle(_translate("MainWindow", "Plugins"))
        self.menuPreferences.setTitle(_translate("MainWindow", "Preferences"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionListWindows.setText(_translate("MainWindow", "ListWindows"))
        self.actionEditors.setText(_translate("MainWindow", "Editors"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionTools.setText(_translate("MainWindow", "Tools"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
